-- =========================================================
-- SCRIPT DE BASE DE DATOS PARA SUPABASE (MÓDULO CLIMA)
-- =========================================================
-- Instrucciones:
-- 1. Entra a Supabase -> SQL Editor -> New Query
-- 2. Pega este código y presiona RUN.
-- =========================================================

CREATE TABLE Clima (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMP WITH TIME ZONE UNIQUE NOT NULL,
    temp_out REAL,
    hum_out REAL,
    viento_vel REAL,
    viento_dir VARCHAR(50),
    lluvia_mm REAL,
    radiacion_solar REAL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear un índice en fecha_hora para acelerar las búsquedas y gráficos
CREATE INDEX idx_clima_fecha ON Clima(fecha_hora DESC);

-- Opcional: Activar RLS (Row Level Security)
-- ALTER TABLE Clima ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Permitir lectura y escritura pública" ON Clima FOR ALL USING (true);
